GET http://localhost:3000/todos/?priority=hIGH&&status=LOW
###

GET http://localhost:3000/todos/2/
###

GET http://localhost:3000/agenda?date=1996/08/04/
###


POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 1,
  "todo": "ram event theme",
  "priority": "HIGH",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "1996-08-04"
}
###

PUT http://localhost:3000/todos/1/
Content-Type: application/json

{
    "status":"LOW"
}
###

DELETE http://localhost:3000/todos/1/
###
